baseurl = "https://samstifter.com/"
title = "Sam Stifter"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

disablePathToLower = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Sam Stifter"
    info = "Software Engineering | Iowa State University"
    description = "Sam Stifter's personal website"
    keywords = "software,engineer,sam,stifter,samuel,student,iowa,state,university"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "images/favicon-32.jpg"
    favicon_16 = "images/favicon-16.jpg"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/samstifter/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/samstifter"

# Menu links
[[menu.main]]
    name = "About Me"
    weight = 1
    url = "/about-me/"
[[menu.main]]
	name = "Projects"
	weight = 2
	url = "/projects/"
[[menu.main]]
	name = "Resume"
	weight = 4
	url = "/resume"
[[menu.main]]
  name = "Contact Me"
  weight = 9
  url = "/contact-me/"
